# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import netsystem_pb2 as netsystem__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in netsystem_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VRManagementStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterUser = channel.unary_unary(
                '/proto_netsystem.VRManagement/RegisterUser',
                request_serializer=netsystem__pb2.RegisterUserRequest.SerializeToString,
                response_deserializer=netsystem__pb2.RegisterUserResponse.FromString,
                _registered_method=True)
        self.UnregisterUser = channel.unary_unary(
                '/proto_netsystem.VRManagement/UnregisterUser',
                request_serializer=netsystem__pb2.UnregisterUserRequest.SerializeToString,
                response_deserializer=netsystem__pb2.Empty.FromString,
                _registered_method=True)
        self.SendPythonScript = channel.unary_unary(
                '/proto_netsystem.VRManagement/SendPythonScript',
                request_serializer=netsystem__pb2.SendPythonScriptRequest.SerializeToString,
                response_deserializer=netsystem__pb2.Empty.FromString,
                _registered_method=True)
        self.SendAudio = channel.unary_unary(
                '/proto_netsystem.VRManagement/SendAudio',
                request_serializer=netsystem__pb2.SendAudioRequest.SerializeToString,
                response_deserializer=netsystem__pb2.Empty.FromString,
                _registered_method=True)
        self.ExData = channel.unary_unary(
                '/proto_netsystem.VRManagement/ExData',
                request_serializer=netsystem__pb2.ExDataRequest.SerializeToString,
                response_deserializer=netsystem__pb2.ExDataResponse.FromString,
                _registered_method=True)


class VRManagementServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterUser(self, request, context):
        """UserManagement   
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendPythonScript(self, request, context):
        """PythonScriptManagement 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendAudio(self, request, context):
        """AudioManagement
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExData(self, request, context):
        """DataManagement 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VRManagementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterUser,
                    request_deserializer=netsystem__pb2.RegisterUserRequest.FromString,
                    response_serializer=netsystem__pb2.RegisterUserResponse.SerializeToString,
            ),
            'UnregisterUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterUser,
                    request_deserializer=netsystem__pb2.UnregisterUserRequest.FromString,
                    response_serializer=netsystem__pb2.Empty.SerializeToString,
            ),
            'SendPythonScript': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPythonScript,
                    request_deserializer=netsystem__pb2.SendPythonScriptRequest.FromString,
                    response_serializer=netsystem__pb2.Empty.SerializeToString,
            ),
            'SendAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.SendAudio,
                    request_deserializer=netsystem__pb2.SendAudioRequest.FromString,
                    response_serializer=netsystem__pb2.Empty.SerializeToString,
            ),
            'ExData': grpc.unary_unary_rpc_method_handler(
                    servicer.ExData,
                    request_deserializer=netsystem__pb2.ExDataRequest.FromString,
                    response_serializer=netsystem__pb2.ExDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto_netsystem.VRManagement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto_netsystem.VRManagement', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VRManagement(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto_netsystem.VRManagement/RegisterUser',
            netsystem__pb2.RegisterUserRequest.SerializeToString,
            netsystem__pb2.RegisterUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto_netsystem.VRManagement/UnregisterUser',
            netsystem__pb2.UnregisterUserRequest.SerializeToString,
            netsystem__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendPythonScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto_netsystem.VRManagement/SendPythonScript',
            netsystem__pb2.SendPythonScriptRequest.SerializeToString,
            netsystem__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto_netsystem.VRManagement/SendAudio',
            netsystem__pb2.SendAudioRequest.SerializeToString,
            netsystem__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto_netsystem.VRManagement/ExData',
            netsystem__pb2.ExDataRequest.SerializeToString,
            netsystem__pb2.ExDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
