# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: netsystem.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fnetsystem.proto\x12\x0fproto_netsystem\"H\n\x13RegisterUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05login\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"[\n\x14RegisterUserResponse\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x19\n\x11landmark_location\x18\x02 \x03(\x01\x12\x16\n\x0elandmark_angle\x18\x03 \x01(\x01\")\n\x15UnregisterUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"q\n\x08Position\x12\x13\n\x0bobject_name\x18\x01 \x01(\t\x12\x13\n\x0bobject_type\x18\x02 \x01(\t\x12\x17\n\x0fobject_location\x18\x03 \x03(\x01\x12\"\n\x1aobject_rotation_quaternion\x18\x04 \x03(\x01\"B\n\x17SendPythonScriptRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x15\n\rpython_script\x18\x02 \x01(\t\"8\n\x10SendAudioRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x12\n\naudio_data\x18\x02 \x01(\x0c\"g\n\rExDataRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x30\n\rposition_list\x18\x02 \x03(\x0b\x32\x19.proto_netsystem.Position\x12\x12\n\naudio_data\x18\x03 \x01(\x0c\"w\n\x0e\x45xDataResponse\x12\x30\n\rposition_list\x18\x01 \x03(\x0b\x32\x19.proto_netsystem.Position\x12\x1a\n\x12python_script_list\x18\x02 \x03(\t\x12\x17\n\x0f\x61udio_data_list\x18\x03 \x03(\x0c\x32\xb0\x03\n\x0cVRManagement\x12]\n\x0cRegisterUser\x12$.proto_netsystem.RegisterUserRequest\x1a%.proto_netsystem.RegisterUserResponse\"\x00\x12R\n\x0eUnregisterUser\x12&.proto_netsystem.UnregisterUserRequest\x1a\x16.proto_netsystem.Empty\"\x00\x12V\n\x10SendPythonScript\x12(.proto_netsystem.SendPythonScriptRequest\x1a\x16.proto_netsystem.Empty\"\x00\x12H\n\tSendAudio\x12!.proto_netsystem.SendAudioRequest\x1a\x16.proto_netsystem.Empty\"\x00\x12K\n\x06\x45xData\x12\x1e.proto_netsystem.ExDataRequest\x1a\x1f.proto_netsystem.ExDataResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'netsystem_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGISTERUSERREQUEST._serialized_start=36
  _REGISTERUSERREQUEST._serialized_end=108
  _REGISTERUSERRESPONSE._serialized_start=110
  _REGISTERUSERRESPONSE._serialized_end=201
  _UNREGISTERUSERREQUEST._serialized_start=203
  _UNREGISTERUSERREQUEST._serialized_end=244
  _EMPTY._serialized_start=246
  _EMPTY._serialized_end=253
  _POSITION._serialized_start=255
  _POSITION._serialized_end=368
  _SENDPYTHONSCRIPTREQUEST._serialized_start=370
  _SENDPYTHONSCRIPTREQUEST._serialized_end=436
  _SENDAUDIOREQUEST._serialized_start=438
  _SENDAUDIOREQUEST._serialized_end=494
  _EXDATAREQUEST._serialized_start=496
  _EXDATAREQUEST._serialized_end=599
  _EXDATARESPONSE._serialized_start=601
  _EXDATARESPONSE._serialized_end=720
  _VRMANAGEMENT._serialized_start=723
  _VRMANAGEMENT._serialized_end=1155
# @@protoc_insertion_point(module_scope)
